name: simple_calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artefact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: calculator_app
        path: target/DevOps_lab-1.0-SNAPSHOT.jar
        retention-days: 7
    - name: Run project
      run: javac DevOps_lab-1.0-SNAPSHOT
     

 
