name: simple_calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artefact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: calculator_app
        path: target/DevOps_lab-1.0-SNAPSHOT.jar
        retention-days: 7
    - name: Checkout code
      uses: actions/checkout@v3.5.3
      
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get Metadata (tags,labels) for Docker images
      id: meta_pytorch
      uses: docker/metadata-action@v4.6.0
      with: 
        images: dimaggi0/lab

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta_pytorch.outputs.tags }}
        labels: ${{ steps.meta_pytorch.outputs.labels }}    
    

 

     

 
